In [12]:
import numpy as np

In [13]:
def read_input(src: str) -> list[list[int]]:
    returning_list = []
    with open(src, 'r') as input_file:
        for row in input_file.read().strip().split('\n'):
            tmp_list = []
            for letter in row:
                tmp_list.append(int(letter))
            returning_list.append(list(tmp_list))
        return returning_list

data = np.array(read_input('example.txt'))
data[:2,:2], data

(array([[3, 0],
        [2, 5]]),
 array([[3, 0, 3, 7, 3],
        [2, 5, 5, 1, 2],
        [6, 5, 3, 3, 2],
        [3, 3, 5, 4, 9],
        [3, 5, 3, 9, 0]]))

In [14]:
np.flip(data, axis=0)

array([[3, 5, 3, 9, 0],
       [3, 3, 5, 4, 9],
       [6, 5, 3, 3, 2],
       [2, 5, 5, 1, 2],
       [3, 0, 3, 7, 3]])

In [15]:
def reset_vis_trees(d:np.array) -> np.array:
    visible_trees = np.ones_like(data)
    visible_trees[1:-1,1:-1] = np.zeros_like(visible_trees[1:-1,1:-1])
    return visible_trees

visible_trees = reset_vis_trees(data)
visible_trees, sum(sum(visible_trees))

(array([[1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1]]),
 16)

In [16]:
visible_trees = reset_vis_trees(data)
def top_direction(dat: np.array, vis_trees: np.array):
    NJ, NI = dat.shape
    for i in range(1,NI-1):
        column = dat[:,i]
        index = np.argmax(column)
        while column.shape[0] > 1:
            vis_trees[index,i] = 1
            column = column[:index]
            index = np.argmax(column) if column.size != 0 else 0

top_direction(data, visible_trees)
print("Top", data, visible_trees, sep="\n", end="\n\n\n")

Top
[[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]
[[1 1 1 1 1]
 [1 1 1 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]




In [17]:
visible_trees = reset_vis_trees(data)
def left_direction(dat: np.array, vis_trees: np.array):
    NI, NJ = dat.shape
    for i in range(1,NJ-1):
        column = dat[i,:]
        index = np.argmax(column)
        while column.shape[0] != 0:
            vis_trees[i,index] = 1
            column = column[:index]
            index = np.argmax(column) if column.size != 0 else 0

left_direction(data,visible_trees)
print("Left", data, visible_trees, sep="\n", end="\n\n\n")

Left
[[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]
[[1 1 1 1 1]
 [1 1 0 0 1]
 [1 0 0 0 1]
 [1 0 1 0 1]
 [1 1 1 1 1]]




In [18]:
def reverse_argmax(self):
    return self.shape[0] - np.argmax(np.flip(np.copy(self)))

np.reverse_argmax = reverse_argmax

In [23]:
visible_trees = reset_vis_trees(data)
def right_direction(dat: np.array, vis_trees: np.array):
    tmp_dat, tmp_vis = np.flip(dat, axis=1), np.flip(vis_trees, axis=1)
    NI, NJ = tmp_dat.shape
    for i in range(1,NJ-1):
        column = tmp_dat[i,:]
        index = np.argmax(column)
        while column.shape[0] != 0:
            tmp_vis[i,index] = 1
            column = column[:index]
            index = np.argmax(column) if column.size != 0 else 0
    vis_trees = np.flip(tmp_vis, axis=1)

right_direction(data,visible_trees)
print("Right", data, visible_trees, sep="\n", end="\n\n\n")

Right
[[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]
[[1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 0 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]




In [24]:
visible_trees = reset_vis_trees(data)
def bottom_direction(dat: np.array, vis_trees: np.array):
    tmp_dat, tmp_vis = np.flip(dat, axis=0), np.flip(vis_trees, axis=0)
    NJ, NI = dat.shape
    for i in range(1,NI-1):
        column = tmp_dat[:,i]
        index = np.argmax(column)
        while column.shape[0] > 1:
            tmp_vis[index,i] = 1
            column = column[:index]
            index = np.argmax(column) if column.size != 0 else 0
    vis_trees = np.flip(tmp_vis, axis=0)

bottom_direction(data, visible_trees)
print("Bottom", data, visible_trees, sep="\n", end="\n\n\n")

Bottom
[[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 1 0 1]
 [1 1 1 1 1]]




In [27]:
data = np.array(read_input('input.txt'))

visible_trees = reset_vis_trees(data)

NI, NJ = visible_trees.shape
dir_dict = {
    'top': top_direction,
    'right': right_direction,
    'bottom_direction': bottom_direction,
    'left': left_direction
}

for direction in dir_dict.keys():
    dir_dict[direction](data, visible_trees)

sum(sum(visible_trees))  


1543